accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name="register"),
    path('login/', auth_views.LoginView.as_view(template_name="account/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('<int:pk>/', views.user_profile_login, name='user_profile_login'),
    path('visitor/<int:pk>/', views.user_profile_customer, name='user_profile_customer'),
    path('blog/draft_blog', views.DraftBlog.as_view(), name='draft_blog'),
]

blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name="all"),
    path("new/", views.CreateBlog.as_view(), name="create_blog"),
    # path("new/", views.CreateBlog, name="create_blog"),
    path("by/<username>/", views.UserBlog.as_view(), name="for_user"),
    path("by/<username>/<int:pk>/", views.BlogDetail.as_view(), name="blog_detail"),
    path("blog/create_success", views.CreateBlogSuccess.as_view(), name="blog_create_success"),
    path('by/<username>/<int:pk>/update', views.UpdateBlog.as_view(), name='update_blog'),
    path('by/<username>/<int:pk>/delete', views.DeleteBlog.as_view(), name='delete_blog'),
    path('by/<username>/<int:pk>/approve_comment', views.approve_comment, name='approve_comment'),
    path('by/<username>/<int:pk>/notapprove_comment', views.notapprove_comment, name='notapprove_comment'),
    path('by/<username>/<int:pk>/comment', views.add_comment, name='add_comment'),
    path('by/<username>/<int:pk>/publish', views.publish_blog, name='publish_blog'),
    path('by/<username>/<int:pk>/delete_comment', views.delete_comment, name='delete_comment'),
]

group/urls.py
from django.urls import path
from group import views

app_name = 'group'

urlpatterns = [
    path('', views.AllGroup.as_view(), name="all_group"),
    path("create/", views.CreateGroup.as_view(), name="create_group"),
    path("create/success", views.CreateGroupSuccess.as_view(), name="create_group_success"),
    path("<slug>/", views.GroupDetail.as_view(), name="group_detail"),
    path("<slug>/join/", views.JoinGroup.as_view(), name="join"),
    path("<slug>/leave/", views.LeaveGroup.as_view(), name="leave"),
    path("<slug>/delete/", views.DeleteGroup.as_view(), name="delete"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite import views
# from accounts import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.Index.as_view(), name='home_page'),
    path('about/', views.About.as_view(), name='about'),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('blog/', include("blog.urls", namespace="blog")),
    path('group/', include("group.urls", namespace="group")),
]

blog/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils import timezone
# import misaka
from group.models import GroupInfo
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.


class Blog(models.Model):
    publisher = models.ForeignKey(User, related_name="blog_publisher", on_delete=models.CASCADE)
    title = models.CharField(max_length=256)
    tag = models.CharField(max_length=256)
    create_time = models.DateTimeField(default=timezone.now)  # 创建时间
    publish_time = models.DateTimeField(blank=True, null=True)  # 发布时间
    content = models.TextField()
    content_html = models.TextField(editable=False)
    group = models.ForeignKey(GroupInfo, related_name="blog_group", on_delete=models.CASCADE)
    modify_time = models.DateTimeField(default=timezone.now)  # 修改时间
    approve_comments = models.BooleanField(default=True)  # 是否允许评论

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        # self.content_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def publish(self):
        self.publish_time = timezone.now()
        self.save()

    def modify(self):
        self.modify_time = timezone.now()
        self.save()

    def get_absolute_url(self):
        return reverse("blog:blog_detail", kwargs={"username": self.publisher.username, "pk": self.pk})

    def approve(self):
        self.approve_comments = True
        self.save()

    def notapprove(self):
        self.approve_comments = False
        self.save()

    def count_comments(self):
        if self.approve_comments == True:
            return self.comments.filter(create_time__isnull=False)
        else:
            return self.comments.filter(create_time__isnull=True)

    def get_comments(self):
        return self.filter(approve_comments=True)  # 挑选出允许comment的blog

    class Meta:
        ordering = ["-create_time"]
        # unique_together = ["publisher", "content"]


class Comments(models.Model):
    relatedblog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')  # 外键连接相关Blog
    publisher = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.publisher

    def get_absolute_url(self):  # 获得每个blog的域名
        return reverse('blog_content', kwargs={'pk': self.relatedblog})

blog/forms.py
from django import forms
from . import models
from django.db.models import Q


class BlogForm(forms.ModelForm):
    class Meta:
        fields = ('title', 'tag', 'content', "group")
        model = models.Blog

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user")
        super(BlogForm, self).__init__(*args, **kwargs)
        # Q() | Q() 用来设置多个过滤条件，逻辑为或
        self.fields["group"].queryset = models.GroupInfo.objects.filter(Q(pk__in=user.user_groups.values_list("group__pk")) | Q(create_user=user))


class CommentsForm(forms.ModelForm):
    class Meta:
        model = models.Comments
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'}),
        }

blog/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import Http404
from django.views import generic
from braces.views import SelectRelatedMixin
from . import forms
from . import models
from django.contrib.auth import get_user_model
from django.db.models import Q
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.core.exceptions import PermissionDenied
User = get_user_model()


class BlogList(SelectRelatedMixin, generic.ListView):
    model = models.Blog
    select_related = ("user", "group")


class UserBlog(generic.ListView):
    model = models.Blog
    template_name = "blog/user_post_list.html"

    def get_queryset(self):
        try:
            self.user = User.objects.prefetch_related("posts").get(username__iexact=self.kwargs.get("username"))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


'''class BlogDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ("user", "group")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )'''


class BlogDetail(generic.DetailView):
    model = models.Blog
    template_name = 'blog/blog_detail.html'


class CreateBlog(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    redirect_field_name = '/'  # 如果没有登录，则自动跳转到登录界面
    fields = ('title', 'tag', 'content', "group")
    # form_class = forms.BlogForm
    model = models.Blog
    template_name = "blog/create_blog.html"
    success_url = reverse_lazy("blog:blog_create_success")
    '''
    # dispatch方法接受请求并最终返回响应。通常，它通过调用另一个方法(如get)来返回响应。把它看作是请求和响应之间的中间人。
    def dispatch(self, *args, **kwargs):
        return super(CreateBlog, self).dispatch(*args, **kwargs)'''

    # get_form_kwargs()：由FormMixin定义，执行表单类实例化过程
    '''def get_form_kwargs(self):
        kwargs = super(CreateBlog, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})  # 将user信息通过kwargs传入forms中，这样forms就能通过重写__init__来获得kwargs传入的参数，在这里也就是user      
        return kwargs'''
    # 或者也可以调用get_form()：由FormMixin定义，调用get_form_kwargs()完成表单类的实例化
    # 调用get_form()就不需要在forms里面重写__init__函数来传递request参数
    # 所以可以不用倒入forms.py中的表格并设置form_class，直接用fields就行
    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        form = super(CreateBlog, self).get_form()
        # Q() | Q() 用来设置多个过滤条件，逻辑为或
        form.fields["group"].queryset = models.GroupInfo.objects.filter(Q(pk__in=self.request.user.user_groups.values_list("group__pk")) | Q(create_user=self.request.user))
        return form

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.publisher = self.request.user
        self.object.save()
        return super().form_valid(form)


class CreateBlogSuccess(generic.TemplateView):
    template_name = 'blog/blog_create_success.html'


class DeleteBlog(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Blog
    select_related = ("publisher", "group")
    template_name = 'blog/delete_blog.html'
    message = 'You deleted this blog successfully'

    def get_object(self, queryset=None):
        object = super(DeleteBlog, self).get_object(queryset=queryset)
        if object.publisher.username != self.request.user.username:
            # if object.user != self.request.user:
            raise PermissionDenied
            # raise Http404()
        return object

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(publisher_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse_lazy('account:user_profile_login', kwargs={'pk': self.request.user.pk})


class UpdateBlog(LoginRequiredMixin, generic.UpdateView):
    redirect_field_name = '/'  # 如果没有登录，则自动跳转到登录界面
    form_class = forms.BlogForm
    model = models.Blog
    template_name = "blog/update_blog.html"  # template会有预设的名称，但还是要显式的定义出来更直观一点

    def form_valid(self, form):  # 设置外键的值，将目前用户和发的blog关联起来
        self.object = form.save(commit=False)
        self.object.modify_time = timezone.now()
        self.object.save()
        return super().form_valid(form)
        # form.instance.modify_time = timezone.now()

    def get_form_kwargs(self):
        kwargs = super(UpdateBlog, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})  # 将user信息通过kwargs传入forms中，这样forms就能通过重写__init__来获得kwargs传入的参数，在这里也就是user
        return kwargs


class DraftBlog(LoginRequiredMixin, generic.ListView):
    redirect_field_name = '/'  # 如果没有登录，则自动跳转到登录界面
    model = models.Blog
    template_name = "blog/draft_list.html"  # template会有预设的名称，但还是要显式的定义出来更直观一点
    def get_queryset(self):
        return models.Blog.objects.filter(publish_time__isnull=True, publisher__exact=self.request.user.pk).order_by('-create_time')


@login_required
def approve_comment(request, username, pk):
    blog = get_object_or_404(models.Blog, pk=pk)
    blog.approve()
    return redirect('blog:blog_detail', username=username, pk=blog.pk)


@login_required
def notapprove_comment(request, username, pk):
    blog = get_object_or_404(models.Blog, pk=pk)
    blog.notapprove()
    return redirect('blog:blog_detail', username=username, pk=blog.pk)


@login_required
def add_comment(request, username, pk):
    blog = get_object_or_404(models.Blog, pk=pk)
    if request.method == 'POST':
        form = forms.CommentsForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.publisher = request.user
            comment.relatedblog = blog
            comment.save()
            return redirect('blog:blog_detail', username=username, pk=blog.pk)
    else:
        form = forms.CommentsForm()
    return render(request, 'blog/comment.html', {'form': form})


@login_required
def publish_blog(request, username, pk):
    blog = get_object_or_404(models.Blog, pk=pk)
    blog.publish()
    return redirect('blog:blog_detail', username=username, pk=pk)


@login_required
def delete_comment(request, username, pk):
    comment = get_object_or_404(models.Comments, pk=pk)
    blog_pk = comment.relatedblog.pk
    comment.delete()
    return redirect('blog:blog_detail', username=username, pk=blog_pk)

templates/blog/_blog.html
<div class="media">
	{% if user.is_authenticated and user.pk == blog.publisher.pk %}
		<h3 class="mr-5"><a href="{% url 'account:user_profile_login' pk=blog.publisher.pk %}">@{{ blog.publisher.username }}</a></h3>
	{% else %}
		<h3 class="mr-5"><a href="{% url 'account:user_profile_customer' pk=blog.publisher.pk %}">@{{ blog.publisher.username }}</a></h3>
	{% endif %}
	<div class="media-body">
		<strong><a href="{% url 'blog:blog_detail' username=blog.publisher.username pk=blog.pk %}">{{ blog.title }}</a></strong>
		<h5>{{ blog.content_html|safe }}</h5>
		<h5>{{ blog.content|safe }}</h5>
			<time class="time">{{ blog.create_time }}</time>
			{% if blog.group %}
				<span class="group-name">in <a href="#">{{ blog.group.name }}</a></span>
			{% endif %}
		</h5>

		<div class="media-footer">
			{% if user.is_authenticated and blog.publisher == user and not hide_delete %}
				<a href="{% url 'blog:delete_blog' username=blog.publisher.username pk=blog.pk %}" title="delete" class="btn btn-simple">
					<span class="fa fa-remove text-danger" aria-hidden="true"></span>
					<span class="text-danger icon-label">Delete</span>
				</a>
			{% endif %}
		</div>
	</div>
</div>

templates/blog/base.html
{% extends "base.html" %}

{% block content %}
<div class="posts-page">
	<div class="container">
		{% block preblog %}{% endblock %}
		{% block blog_content %}{% endblock %}
		{% block postblog %}{% endblock %}
	</div>
</div>
{% endblock %}

templates/blog/blog_create_success.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h3>Congratulation, you created a draft successfully!</h3>
    <p>If you want to post your draft, please click draft button to select which one you want to publish.</p>
</div>

{% endblock %}

templates/blog/blog_detail.html
{% extends "blog/base.html" %}

{% block blog_content %}

    {% if blog.publish_time %}
        <h1 class='posttitle loader'>{{ blog.title }}</h1>
        <div class="date postdate">
            <p>The blog was published at: {{ blog.publish_time }}</p>
        </div>
        <p class='postcontent' >{{ blog.content|safe|linebreaksbr }}</p>
        <div class="date postdate">
            <time class="time">Posted at: {{ blog.publish_time }}</time>
            {% if blog.group %}
                <span class="group-name">in <a href="{% url 'group:group_detail' slug=blog.group.slug %}">{{ blog.group.name }}</a></span>
            {% endif %}
        </div>
        {% if user.is_authenticated and blog.publisher.pk == user.pk %}
            <a class="btn btn-primary" href="{% url 'blog:update_blog' username=user.username pk=blog.pk %}"><span class="fa fa-pencil">Edit</span></a>
            <a class="btn btn-primary" href="{% url 'blog:delete_blog' username=user.username pk=blog.pk %}"><span class="fa fa-remove">Delete</span></a>
            {% if blog.approve_comments %}
                <a class="btn btn-primary" href="{% url 'blog:notapprove_comment' username=user.username pk=blog.pk %}"><span class="fa fa-remove">Forbid Comments</span></a>
            {% else %}
                <a class="btn btn-primary" href="{% url 'blog:approve_comment' username=user.username pk=blog.pk %}"><span class="fa fa-remove">Approve Comments</span></a>
            {% endif %}
        {% endif %}
        <hr>
        {% if blog.approve_comments %}
            <a class="btn btn-primary btn-comment" href="{% url 'blog:add_comment' username=user.username pk=blog.pk %}">Add Comment</a>
            <div class="container">
                {% for comment in blog.comments.all %}
                    <br>
                    {% if user.is_authenticated or blog.approve_comments %}
                        {% if user.is_authenticated and user.pk == comment.publisher.pk %}
                            <a class="btn btn-primary" href="{% url 'blog:delete_comment' username=user.username pk=comment.pk %}"><span class="fa fa-remove">Delete Comment</span></a>
                        {% endif %}
                        <p>{{ comment.content|safe|linebreaks }}</p>
                        <p>Posted by: <strong>{{ comment.publisher }}</strong></p>
                    {% endif %}
                    {% empty %}
                    <p>No comments here.</p>
                {% endfor %}
            </div>
        {% else %}
            <p>Comments are forbidden now</p>
        {% endif %}
    {% else %}
        {% if user.is_authenticated and blog.publisher.pk == user.pk %}
            <h1 class='posttitle loader'>{{ blog.title }}</h1>
            <div class="date postdate">
                <time class="time">Created at: {{ blog.create_time }}</time>
                {% if blog.group %}
                    <span class="group-name">in <a href="{% url 'group:group_detail' slug=blog.group.slug %}">{{ blog.group.name }}</a></span>
                {% endif %}
            </div>
            <p class='postcontent' >{{ blog.content|safe|linebreaksbr }}</p>
            <a class="btn btn-primary" href="{% url 'blog:update_blog' username=user.username pk=blog.pk %}"><span class="fa fa-pencil">Edit</span></a>
            <a class="btn btn-primary" href="{% url 'blog:delete_blog' username=user.username pk=blog.pk %}"><span class="fa fa-remove">Delete</span></a>
            {% if not blog.publish_time %}
                <a class="btn btn-primary" href="{% url 'blog:publish_blog' username=user.username pk=blog.pk %}"><span class="fa fa-pencil">Publish</span></a>
            {% endif %}
            <hr>
        {% else %}
            <p>Page does not exist!</p>
            <a class="btn btn-outline-dark" href="{% url 'home_page' %}">Home Page</a>
        {% endif %}
    {% endif %}

{% endblock %}

templates/blog/blog_list.html
{% extends "blog/base.html" %}

{% block preblog %}

<div class="col-md-4">
	{% if request.user.is_authenticated %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">Your Groups</h5>
			<ul class="list-unstyled">
				{% for member_group in get_user_groups %}
				    <li class="group li-with-bullet">
					    <a href="{% url 'group:group_detail' slug=member_group.group.slug %}">{{ member_group.group.name }}</a>
				    </li>
				{% endfor %}

			</ul>
		</div>
	</div>
	{% endif %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">All groups</h5>
			<ul class="list-unstyled">
				{# {% get_other_groups as other_groups %} #}
				{% for other_group in get_other_groups %}
					<li class="group li-with-bullet"><a href="{% url 'group:group_detail' slug=other_group.slug %}">{{ other_group.name }}</a></li>
				{% endfor %}
			</ul>

		</div>
	</div>
</div>

{% endblock %}


{% block post_content %}

<div class="col-md-8">
	{% for post in post_list %}
        {% include "blog/_blog.html" %}
	{% endfor %}
</div>

{% endblock %}

templates/blog/comment.html
{% extends 'blog/base.html' %}
{% load bootstrap4 %}

{% block content %}

    <h1>New comment</h1>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="save btn btn-default">Post Comment</button>
        {% endbuttons %}
    </form>
    <script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

templates/blog/create_blog.html
{% extends "blog/base.html" %}
{% load bootstrap4 %}

{% block blog_content %}

<h1>Create New Post</h1>
<h4>Now it's time to writing down your new blog!</h4>
<form method="POST" action="{% url 'blog:create_blog' %}" id="postForm">
	{% csrf_token %}
	{% bootstrap_form form %}
	<hr>
	{% buttons %}
		<button type="submit" class="btn btn-primary btn-large">Save</button>
	{% endbuttons %}
</form>

<script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

templates/blog/delete_blog.html
{% extends "blog/base.html" %}

{% block blog_content %}
<h3>Are you sure you want to delete this post?</h3>

<div class="posts">
	{% include "blog/_blog.html" with blog=object hide_delete=True %}
</div>

<form method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	<a href="{% url 'blog:blog_detail' username=user.username pk=object.pk %}" class="btn btn-light btn-large">Cancel</a>
</form>

{% endblock %}

templates/blog/draft_list.html
{% extends 'blog/base.html' %}

{% block content %}

<div class="centerstage">
    <h1>Blog</h1>
    {% for blog in blog_list %}
        <div class="post">
            <h1><a href="{% url 'blog:blog_detail' username=user.username pk=blog.pk %}">{{ blog.title }}</a></h1>
            <div class="date">
                <p>Created on: {{ blog.create_time|date:"D M Y"}}</p>
            </div>
            <a href="{% url 'blog:blog_detail' username=user.username pk=blog.pk %}">Comments: {{ blog.count_comments.count }}</a>
        </div>
    {% endfor %}

</div>

{% endblock %}

templates/blog/update_blog.html
{% extends "blog/base.html" %}
{% load bootstrap4 %}

{% block blog_content %}

<h1>Update Post</h1>
<h4>Edit your blog here!</h4>
<form method="POST" id="postForm">
	{% csrf_token %}
	{% bootstrap_form form %}
	<hr>
	{% buttons %}
		<button type="submit" class="btn btn-primary btn-large">Save</button>
	{% endbuttons %}
</form>

<script>var editor = new MediumEditor('.editable');</script>

{% endblock %}