accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name="register"),
    path('login/', auth_views.LoginView.as_view(template_name="account/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('<int:pk>/', views.user_profile_login, name='user_profile_login'),
    path('visitor/<int:pk>/', views.user_profile_customer, name='user_profile_customer'),
    path('blog/draft_blog', views.DraftBlog.as_view(), name='draft_blog'),
]

blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name="all"),
    path("new/", views.CreateBlog.as_view(), name="create_blog"),
    # path("new/", views.CreateBlog, name="create_blog"),
    path("by/<username>/", views.UserBlog.as_view(), name="for_user"),
    path("by/<username>/<int:pk>/", views.BlogDetail.as_view(), name="blog_detail"),
    path("blog/create_success", views.CreateBlogSuccess.as_view(), name="blog_create_success"),
    path('by/<username>/<int:pk>/update', views.UpdateBlog.as_view(), name='update_blog'),
    path('by/<username>/<int:pk>/delete', views.DeleteBlog.as_view(), name='delete_blog'),
    path('by/<username>/<int:pk>/approve_comment', views.approve_comment, name='approve_comment'),
    path('by/<username>/<int:pk>/notapprove_comment', views.notapprove_comment, name='notapprove_comment'),
    path('by/<username>/<int:pk>/comment', views.add_comment, name='add_comment'),
    path('by/<username>/<int:pk>/publish', views.publish_blog, name='publish_blog'),
    path('by/<username>/<int:pk>/delete_comment', views.delete_comment, name='delete_comment'),
]

group/urls.py
from django.urls import path
from group import views

app_name = 'group'

urlpatterns = [
    path('', views.AllGroup.as_view(), name="all_group"),
    path("create/", views.CreateGroup.as_view(), name="create_group"),
    path("create/success", views.CreateGroupSuccess.as_view(), name="create_group_success"),
    path("<slug>/", views.GroupDetail.as_view(), name="group_detail"),
    path("<slug>/join/", views.JoinGroup.as_view(), name="join"),
    path("<slug>/leave/", views.LeaveGroup.as_view(), name="leave"),
    path("<slug>/delete/", views.DeleteGroup.as_view(), name="delete"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite import views
# from accounts import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.Index.as_view(), name='home_page'),
    path('about/', views.About.as_view(), name='about'),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('blog/', include("blog.urls", namespace="blog")),
    path('group/', include("group.urls", namespace="group")),
]

group/models.py
from django.db import models
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django.utils import timezone
User = get_user_model()
# import misaka
from blog import models as blog_models
# https://docs.djangoproject.com/en/2.0/howto/custom-template-tags/#inclusion-tags
# This is for the in_group_members check template tag
from django import template
register = template.Library()

# Create your models here.
class GroupInfo(models.Model):
    name = models.CharField(max_length=255, unique=True)
    create_user = models.ForeignKey(User, related_name='create_user', on_delete=models.CASCADE)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User, through="GroupMember")
    create_time = models.DateTimeField(default=timezone.now)  # 创建时间

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        # self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("group:group_detail", kwargs={"slug": self.slug})

    def published_blog(self):
        return blog_models.Blog.objects.filter(group__exact=self, publish_time__isnull=False).count()

    class Meta:
        ordering = ["-create_time"]


class GroupMember(models.Model):
    group = models.ForeignKey(GroupInfo, related_name='memberships', on_delete=models.CASCADE)
    member = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)
    join_time = models.DateTimeField(default=timezone.now)  # 创建时间

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("group", "member")

group/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from group.models import GroupInfo
# from django.contrib.auth.models import User


class GroupInfoForm(forms.ModelForm):
    class Meta:
        model = GroupInfo
        # fields = ('title', 'tag', 'content')
        fields = ('name', 'description')
        widgets = {
            # 'publisher': forms.TextInput(attrs={'class': 'textinputclass'}),
            'name': forms.TextInput(attrs={'class': 'textinputclass'}),
            'description': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'}),
        }
        error_messages = {
            'name': {'required': "please give the group a title",},
        }

group/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from group.models import GroupInfo, GroupMember
from group import models
from blog import models as blog_models
from group.forms import GroupInfoForm
from django.urls import reverse_lazy


class CreateGroup(LoginRequiredMixin, generic.CreateView):
    redirect_field_name = '/'  # 如果没有登录，则自动跳转到登录界面

    # fields = ("name", "description")
    form_class = GroupInfoForm
    model = GroupInfo
    template_name = 'group/create_group.html'
    success_url = reverse_lazy("group:create_group_success")

    def form_valid(self, form):
        form.instance.create_user = self.request.user
        return super().form_valid(form)


class CreateGroupSuccess(generic.TemplateView):
    template_name = 'group/group_create_success.html'


class GroupDetail(generic.DetailView):
    model = GroupInfo
    template_name = 'group/group_detail.html'


class AllGroup(generic.ListView):
    model = GroupInfo
    template_name = 'group/group_list.html'


class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("group:group_detail", kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(GroupInfo, slug=self.kwargs.get("slug"))
        try:
            GroupMember.objects.create(member=self.request.user, group=group)
        except IntegrityError:
            messages.warning(self.request, ("Warning, already a member of {}".format(group.name)))
        else:
            messages.success(self.request, "You are now a member of the {} group.".format(group.name))
        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("group:group_detail", kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        try:
            membership = models.GroupMember.objects.filter(member=self.request.user, group__slug=self.kwargs.get("slug")).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request, "You can't leave this group because you aren't in it.")
        else:
            membership.delete()
            messages.success(self.request, "You have successfully left this group.")
        return super().get(request, *args, **kwargs)


class DeleteGroup(LoginRequiredMixin, generic.DeleteView):
    model = GroupInfo
    template_name = "group/delete_confirm.html"
    success_url = reverse_lazy('group:all_group')

templates/group/base.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <div class="row">
    {% block pregroup %}
    {% endblock %}
    {% block group_content %}
    {% endblock %}
    {% block postgroup %}
    {% endblock %}
  </div>
</div>

{% endblock %}

templates/group/create_group.html
{% extends "group/base.html" %}
{% load bootstrap4 %}

{% block group_content %}

<div class="container">
  <h4>Create A New Group</h4>
  <form method="POST" action="{% url 'group:create_group' %}" id="groupForm">
  	{% csrf_token %}
  	{% bootstrap_form form %}
    {% buttons %}
  		<button type="submit" class="btn btn-primary btn-large">Create</button>
  	{% endbuttons %}
  </form>
</div>

{% endblock %}

templates/group/delete_confirm.html
{% extends "group/base.html" %}

{% block group_content %}
<h3>Are you sure you want to delete this post?</h3>

<div class="posts">
    <p>{{groupinfo.name}}</p>
</div>

<form method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	<a href="{% url 'group:group_detail' slug=groupinfo.slug %}" class="btn btn-light btn-large">Cancel</a>
</form>

{% endblock %}

templates/group/group_create_success.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h1>Congratulation, you created a new group successfully!</h1>
</div>

{% endblock %}

templates/group/group_detail.html
{% extends "group/base.html" %}

{% block pregroup %}

<div class="container">
  <h1>{{groupinfo.name}}</h1>
  <h2> Current Member Count: {{groupinfo.members.count}}</h2>
  <div class="content">
	{% if user.username != groupinfo.create_user.username %}
  		{% if user in groupinfo.members.all %}
  			<a href="{% url 'group:leave' slug=groupinfo.slug %}" class="btn btn-lg btn-warning"><span class="fa fa-times-circle-o"></span> Leave </a>
  		{% else %}
  			<a href="{% url 'group:join' slug=groupinfo.name %}" class="btn btn-lg btn-warning"><span class="fa fa-check-circle-o"></span> Join </a>
  		{% endif %}
	{% else %}
	  	{% if user.is_authenticated %}
	  		<a href="{% url 'group:delete' slug=groupinfo.slug %}" class="btn btn-lg btn-warning"><span class="fa fa-times-circle-o"></span> Delete Group </a>
	  	{% endif %}
	{% endif%}
  </div>
</div>

{% endblock %}


{% block group_content %}

<div class="col-md-8">
	{% if user.is_authenticated and user.pk == groupinfo.create_user.pk %}
		<h3 class="mr-5"><p>Group was created by: <a href="{% url 'account:user_profile_login' pk=groupinfo.create_user.pk %}">@{{ groupinfo.create_user.username }}</a></p></h3>
	{% else %}
		<h3 class="mr-5"><p>Group was created by: <a href="{% url 'account:user_profile_customer' pk=groupinfo.create_user.pk %}">@{{ groupinfo.create_user.username }}</a></p></h3>
	{% endif %}
	<hr>
	<h2>Group members:</h2>
	{% if groupinfo.members.count == 0 %}
		<h2> No members in this group yet! </h2>
	{% else %}
		{% for member in groupinfo.members.all %}
			<div class="media">
				{% if user.is_authenticated and user.pk == member.pk %}
					<h3 class="mr-5"><a href="{% url 'account:user_profile_login' pk=member.pk %}">@{{ member.username }}</a>
						{% for membership in groupinfo.memberships.all %}
							{% if membership.member.pk == member.pk %}
								<p>joined at {{membership.join_time}}</p>
							{% endif %}
						{% endfor %}
					</h3>
				{% else %}
					<h3 class="mr-5"><a href="{% url 'account:user_profile_customer' pk=member.pk %}">@{{ member.username }}</a>
						{% for membership in groupinfo.memberships.all %}
							{% if membership.member.pk == member.pk %}
								<p>joined at {{membership.join_time}}</p>
							{% endif %}
						{% endfor %}
					</h3>
				{% endif %}
			</div>
		{% endfor %}
	{% endif %}
	<hr>
	<h2>Published blogs:</h2>
	{% if groupinfo.blog_group.count == 0 %}
		<h2> No blogs in this group yet! </h2>
	{% else %}
		{% for blog in groupinfo.blog_group.all %}
			{% if blog.publish_time != None %}
				{% include "blog/_blog.html" %}
			{% endif %}
		{% endfor %}
	{% endif %}
</div>

{% endblock %}

templates/group/group_list.html
{% extends "group/base.html" %}

{% block pregroup %}

<div class="col-md-8">
	<div class="content">
		{% if user.is_authenticated %}
			<h2>Hello, <a href="{% url 'account:user_profile_login' pk=user.pk %}">@{{ user.username }}</a></h2>
    	{% endif %}
		<h2>Welcome to the Groups Page!</h2>
		<p>Here are all groups. Select a Group with a shared interest!</p>
		<hr>
	</div>
	{% if user.is_authenticated %}
		<a href="{% url 'group:create_group' %}" class="btn btn-warning" role="button"><span class="fa fa-plus"></span> Create New Group!</a>
	{% endif %}
</div>

{% endblock %}


{% block group_content %}

<div class="col-md-8">
	<div class="list-group">
		{% for group in object_list %}
		<a href="{% url 'group:group_detail' slug=group.slug %}" class="list-group-item list-group-item-action flex-column align-items-start">
			<h3 class="mb-1">{{ group.name }}</h3>
			<p class="mb-1">{{ group.description|safe }}</p>
			<p class="mb-1">{{ group.description_html|safe }}</p>
			<div class="d-flex w-40 justify-content-between">
				<small class="text-muted"><span class="badge badge-secondary">		</span>members: {{ group.members.count }}</small>
				<small class="text-muted"><span class="badge badge-secondary">		</span>blogs: {{ group.published_blog }}</small>
				<small class="text-muted"><span class="badge badge-secondary">		</span>created by: {{ group.create_user }}</small>
				<span></span><span></span>
			</div>
		</a>
		{% endfor %}
	</div>
</div>

{% endblock %}