accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name="register"),
    path('login/', auth_views.LoginView.as_view(template_name="account/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('<int:pk>/', views.user_profile_login, name='user_profile_login'),
    path('visitor/<int:pk>/', views.user_profile_customer, name='user_profile_customer'),
    path('blog/draft_blog', views.DraftBlog.as_view(), name='draft_blog'),
]

blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name="all"),
    path("new/", views.CreateBlog.as_view(), name="create_blog"),
    # path("new/", views.CreateBlog, name="create_blog"),
    path("by/<username>/", views.UserBlog.as_view(), name="for_user"),
    path("by/<username>/<int:pk>/", views.BlogDetail.as_view(), name="blog_detail"),
    path("blog/create_success", views.CreateBlogSuccess.as_view(), name="blog_create_success"),
    path('by/<username>/<int:pk>/update', views.UpdateBlog.as_view(), name='update_blog'),
    path('by/<username>/<int:pk>/delete', views.DeleteBlog.as_view(), name='delete_blog'),
    path('by/<username>/<int:pk>/approve_comment', views.approve_comment, name='approve_comment'),
    path('by/<username>/<int:pk>/notapprove_comment', views.notapprove_comment, name='notapprove_comment'),
    path('by/<username>/<int:pk>/comment', views.add_comment, name='add_comment'),
    path('by/<username>/<int:pk>/publish', views.publish_blog, name='publish_blog'),
    path('by/<username>/<int:pk>/delete_comment', views.delete_comment, name='delete_comment'),
]

group/urls.py
from django.urls import path
from group import views

app_name = 'group'

urlpatterns = [
    path('', views.AllGroup.as_view(), name="all_group"),
    path("create/", views.CreateGroup.as_view(), name="create_group"),
    path("create/success", views.CreateGroupSuccess.as_view(), name="create_group_success"),
    path("<slug>/", views.GroupDetail.as_view(), name="group_detail"),
    path("<slug>/join/", views.JoinGroup.as_view(), name="join"),
    path("<slug>/leave/", views.LeaveGroup.as_view(), name="leave"),
    path("<slug>/delete/", views.DeleteGroup.as_view(), name="delete"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite import views
# from accounts import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.Index.as_view(), name='home_page'),
    path('about/', views.About.as_view(), name='about'),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('blog/', include("blog.urls", namespace="blog")),
    path('group/', include("group.urls", namespace="group")),
]

templates/about.html
{% extends 'base.html' %}

{% block content %}

<div class="centerstage">
    <h1>About</h1>

</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
        <!-- Medium Style Editor API -->
        <script src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js"></script>
        <link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
        <!-- Fonts API -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">
        <!-- Local css file -->
        {% load static %}  <!-- 一定要加在本地css文件之前，否则会报错 -->
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    </head>

    <body class='loader'>
        <nav class="navbar navbar-expand-lg bg-light techfont">
            <div class="container">
                <div class="navbar-nav align-items-center">
                    <a class="navbar-brand bigbrand" href="{% url 'home_page' %}">Social Group</a>
                    <a class="nav-item nav-link" href="{% url 'about' %}">About</a>
                    <a class="nav-item nav-link" href="https://www.github.com">Github</a>
                    <a class="nav-item nav-link" href="https://www.linkedin.com">LinkedIn</a>
                </div>
                <div class="navbar-nav align-items-center ml-auto">
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'account:user_profile_login' pk=user.pk %}">Hello: {{ user.username }}</a>
                        <a class="nav-item nav-link" href="{% url 'blog:create_blog' %}">New Post</a>
                        <a class="nav-item nav-link" href="{% url 'account:draft_blog' %}">Drafts</a>
                        <a class="nav-item nav-link" href="{% url 'group:all_group' %}">All Group</a>
                        <a class="nav-item nav-link" href="{% url 'group:create_group' %}" class="btn btn-simple">Create Group</a>
                        <a class="nav-item nav-link" href="{% url 'account:user_profile_login' pk=user.pk %}">Profile</a>
                        <a class="nav-item nav-link" href="{% url 'account:logout' %}">Log out</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{% url 'group:all_group' %}">
                            <span class="fa fa-user" aria-hidden="true">All Group</span>
                        </a>
                        <a class="nav-item nav-link" href="{% url 'account:login' %}" aria-label="Login">
                            <span class="fa fa-user" aria-hidden="true">Log in</span>
                        </a>
                        <a class="nav-item nav-link" href="{% url 'account:register' %}">
                            <span class="fa fa-user" aria-hidden="true">Sign up</span>
                        </a>
                    {% endif %}
                </div>
            </div>
        </nav>
        {# The actual blog posts #}
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    <div class="blog_posts">
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
        {# Registration page #}
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    <div class="blog_posts">
                        {% block body_block %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
        {# Profile page #}
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    <div class="blog_posts">
                        {% block profile_block %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
        <!-- Local js file -->
        <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="centerstage">
    <h1>Welcome to Social Group!</h1>

</div>

{% endblock %}

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
<script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>
</head>
<body>
    <script type="text/javascript">
				$("#name").attr("你所要赋予的值");
				</script>
    <p id="name">$("#name")</p>
</body>

</html>